### ISSUE TITLE
unable to uninstall

### ISSUE THREAD

**Issue by topkool** [ste26054/redmine_leaves_holidays#15] opened 2015-10-10 23:26 UTC
Here is the log with Redmine 3.1.1:

~~~
Migrating redmine_leaves_holidays (Redmine Leave Holidays plugin)...
== 20150928102600 AddDataToLeaveEvents: reverting =============================
-- remove_column(:leave_events, :event_data, :text)
   -> 0.2656s
== 20150928102600 AddDataToLeaveEvents: reverted (0.2749s) ====================

== 20150605145600 AddLeaveRenewalDatePrefs: reverting =========================
-- remove_column(:leave_preferences, :leave_renewal_date, :date, {:null=>false})
   -> 0.2502s
== 20150605145600 AddLeaveRenewalDatePrefs: reverted (0.2504s) ================

== 20150604170900 RemoveDefaultVote: reverting ================================
rake aborted!
An error has occurred, all later migrations canceled:

ActiveRecord::IrreversibleMigration/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration/command_recorder.rb:65:in `inverse_of'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration/command_recorder.rb:50:in `record'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration/command_recorder.rb:83:in `change_column_default'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
/usr/share/redmine-3.1.1/plugins/redmine_leaves_holidays/db/migrate/20150604170900_remove_default_vote.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:603:in `block in exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:492:in `block (2 levels) in revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration/command_recorder.rb:38:in `revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:492:in `block in revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:639:in `suppress_messages'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:491:in `revert'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:603:in `exec_migration'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:1043:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:827:in `down'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-4.2.4/lib/active_record/migration.rb:802:in `migrate'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:481:in `migrate_plugin'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:453:in `migrate'
/usr/share/redmine-3.1.1/lib/redmine/plugin.rb:464:in `migrate'
/usr/share/redmine-3.1.1/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
~~~

**Comment by ste26054** [comment] 2015-10-12 09:05
Hello, the issue is fixed in latest pr

**Closed by ste26054** 2015-10-12 09:05 UTC

**Comment by topkool** [comment] 2015-10-12 09:18
It works, thanks
